### ISSUE TITLE
How I can  make Simple Ajax Uploader (progress bar) work with OPCache in PHP 5.5?

### ISSUE THREAD

**Issue by osroflo** [LPology/Simple-Ajax-Uploader#74]
I was working with Simple Ajax Uploader in php 5.3 and I was able to install the APC php extension and everything was working great. But now I moved to php 5.5 and I realized that APC is not able to be installed in php5.5

/tmp/pear/temp/APC/apc_compile.c:2417:9: error: ‘zend_trait_precedence’ has
no member named ‘function’
make: **\* [apc_compile.lo] Error 1
ERROR: `make' failed

According to https://serverpilot.io/community/articles/how-to-install-php-apc-extension.html   PHP 5.5  is integrating OpCode Cache by default and APC is not able to be installed.

I tested Simple Ajax Uploader  in php 5.5 and it was able to upload file however the progress bar is not working (obviously).    

My Question is: how I can  make Simple Ajax Uploader (progress bar) work with OpCode Cache? or How can I make it work in newest PHP versions?

**Comment by eaglexdev** [comment]
Thanks for your help. I will try it soon.
